version: '2'
services:
  radiusd:
    image: radiii
    environment:
      - RADIII_TIMEZONE=America/Detroit
      - RADIII_BASEURL=http://library.thegdl.org:4500
      - RADIII_MAX_FINE=3.99
      - RADIII_CLIENT_IP=192.168.128.0/24
      - RADIII_CLIENT_SECRET=testing123
    ports:
      - "1812:1812/udp"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
          gateway: 192.168.128.1