version: '2.1'
services:
  radiusd:
    image: radiii
    command: -f -l stdout
    environment:
      - RADIII_TIMEZONE=America/Detroit
      - RADIII_BASEURL=http://library.thegdl.org:4500
      - RADIII_MAX_FINE=3.99
      - RADIII_RADIUS_CLIENT_SUBNET=192.168.0.0/24
      - RADIII_RADIUS_CLIENT_SECRET=testing123
    volumes:
      - raddb:/etc/raddb
    ports:
      - "1812:1812/udp"
volumes:
  raddb:

